### ISSUE TITLE
dora support

### ISSUE THREAD

**Issue by elen07zz** [Jelosus2/Lora_Easy_Training_Colab#1]
Hi, I was wondering if there will be support for DoRA

**Comment by Jelosus2** [comment]
Hello, I never trained Dora myself, but I think the backend (scripts) has support for them. You should check the options in your UI; if you don't have them, it's probably because you need to update it.

**Comment by Jelosus2** [comment]
Issue with more than a week of inactivity; I'll proceed to close it.
