### ISSUE TITLE
Getting "not found" when entering the tunnel

### ISSUE THREAD

**Issue by RorutopThe2nd** [Jelosus2/Lora_Easy_Training_Colab#3]
Disappointing to see the tunnel not working, even with Ngrok.. It's my first time using this colab notebook. My browser is Librewolf
![image](https://github.com/user-attachments/assets/ca2fa9ad-8577-4803-b202-b0dfa3320e72)

**Comment by Jelosus2** [comment]
And I'm dissapointed that you didn't read the description of the cell nor [the guide](https://civitai.com/articles/4409) that explains how to use the collab properly before posting an issue here. I've tested both services and both work so I'll be closing the issue, have a nice day!

**Comment by RorutopThe2nd** [comment]
Someone told me that now, mb lol
